"""Add is_disabled column to ticket

Revision ID: 00d3d7bcd5cc
Revises: 3d869464a422
Create Date: 2025-05-27 01:19:05.014640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d3d7bcd5cc'
down_revision = '3d869464a422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disabled_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('disabled_seats', sa.Integer(), nullable=True))

    with op.batch_alter_table('game_area', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disabled_available_seats', sa.Integer(), nullable=True))

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_disabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('is_disabled')

    with op.batch_alter_table('game_area', schema=None) as batch_op:
        batch_op.drop_column('disabled_available_seats')

    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.drop_column('disabled_seats')
        batch_op.drop_column('disabled_price')

    # ### end Alembic commands ###
